PROCESSOS_SAP2502 = {
    "Application Platform and Infrastructure": {
        "1NN": "Business Event Handling",
        "1NJ": "Responsibility Management",
        "31N": "Situation Handling"
    },
    "Asset Management": {
        "BH1": "Corrective Maintenance",
        "BH2": "Emergency Maintenance",
        "4VT": "Improvement Maintenance",
        "3YE": "Integration with Asset Central Foundation",
        "43R": "Maintenance Resource Scheduling",
        "4WM": "Operational and Overhead Maintenance",
        "BJ2": "Preventive Maintenance",
        "4HI": "Proactive Maintenance",
        "4HH": "Reactive Maintenance",
        "4RV": "SAP Maintenance Assistant"
    },
    "Database and Data Management": {
        "53M": "ABAP Core Data Services Extraction for SAP Data Intelligence",
        "53L": "ABAP Core Data Services Extraction for SAP Datasphere",
        "6N4": "ABAP Core Data Services Extraction for SAP HANA",
        "35D": "Core Data Services-Based Extraction with SAP S/4HANA Cloud Public Edition",
        "JB1": "Core HR with SAP SuccessFactors Employee Central",
        "BH3": "Data Migration to SAP S/4HANA from SAP",
        "2Q2": "Data Migration to SAP S/4HANA from Staging",
        "5LE": "Data Protection and Privacy",
        "4AP": "Data Quality Management for Business Partner",
        "4AQ": "Data Quality Management for Product",
        "1FD": "Employee Integration - SAP S/4HANA Enablement",
        "1YB": "Import Connection Setup with SAP Analytics Cloud",
        "1KA": "Information Lifecycle Management",
        "2UZ": "Integration with Data Quality Management",
        "55E": "Lot Size of One with Advanced Variant Configuration",
        "1RK": "Mass Load and Mass Maintenance for Business Partner",
        "1RM": "Mass Load and Mass Maintenance for Product",
        "1N7": "Mass Processing for Business Partner",
        "1N5": "Mass Processing for Product",
        "1N3": "Master Data Consolidation for Business Partner",
        "1N1": "Master Data Consolidation for Product",
        "1RO": "Master Data Integration",
        "3UP": "Payroll Processing with SAP ERP HCM Payroll",
        "1NL": "Payroll Processing with SAP SuccessFactors Employee Central Payroll",
        "54U": "Produce and Sell Standard Products - Inventory Management",
        "54V": "Produce and Sell Standard Products - Warehouse Managed",
        "1NJ": "Responsibility Management",
        "3N5": "SAP Enable Now Integration",
        "1W4": "Subsidiary Integration of SAP S/4HANA Cloud to Central Finance"
    },
    "Finance": {
        "6IL": "Account Reconciliation - SAP Solution Extensions by BlackLine",
        "1GA": "Accounting and Financial Close - Group Ledger IFRS",
        "2VA": "Accounting and Financial Close - Group Ledger US GAAP",
        "J58": "Accounting and Financial Close",
        "J60": "Accounts Payable",
        "J59": "Accounts Receivable",
        "33Q": "Actual Costing",
        "J77": "Advanced Bank Account Management",
        "4X8": "Advanced Bank Statement Automation",
        "J78": "Advanced Cash Operations",
        "1QM": "Advanced Credit Management",
        "4HG": "Advanced Financial Closing Integration",
        "4MT": "Advanced Payment Management",
        "2YM": "Application Interface to Retrieve Payment Files",
        "6VB": "Asset Accounting - Additional Depreciation Keys for Local GAAPs",
        "1GB": "Asset Accounting - Group Ledger IFRS",
        "33F": "Asset Accounting - Group Ledger US GAAP",
        "5HG": "Asset Accounting – Additional Depreciation Area",
        "J62": "Asset Accounting",
        "6X6": "Asset Retirement Obligation - Group Ledger US GAAP",
        "5IT": "Asset Retirement Obligation - IFRS",
        "56E": "Asset Retirement Obligation",
        "1GF": "Asset Under Construction - Group Ledger IFRS",
        "33G": "Asset Under Construction - Group Ledger US GAAP",
        "5KF": "Asset Under Construction – Additional Depreciation Area",
        "BFH": "Asset Under Construction",
        "3AB": "Automated Provisioning via SAP Cloud Identity Access Governance",
        "1S4": "Automatic Market Rates Management",
        "2O0": "Bank Fee Management",
        "2O2": "Bank Guarantee Management - Group Ledger IFRS",
        "34F": "Bank Guarantee Management - Group Ledger US GAAP",
        "2NZ": "Bank Guarantee Management",
        "1EG": "Bank Integration with File Interface",
        "16R": "Bank Integration with SAP Multi-Bank Connectivity",
        "BFA": "Basic Bank Account Management",
        "BFB": "Basic Cash Operations",
        "BD6": "Basic Credit Management",
        "3WZ": "Bond Management - Group Ledger IFRS",
        "3X0": "Bond Management - Group Ledger US GAAP",
        "3WY": "Bond Management",
        "1MV": "Cash Application Integration",
        "1GO": "Cash Journal",
        "BFC": "Collections and Dispute Management",
        "2UT": "Complementary Invoice - Pricing",
        "1J2": "Compliance Formats - Support Preparation",
        "24J": "Compliance Management with SAP Global Trade Services",
        "2OH": "Continuous Control Monitoring with SAP Process Control",
        "54D": "Control Credit for Taxes on Assets",
        "3KY": "Control Monitoring with SAP Risk and Assurance Management",
        "1RY": "Credit Agency Integration",
        "1S0": "Customer Payments",
        "2U1": "Customs Management with SAP Global Trade Services",
        "1X7": "Debt and Investment Management - Group Ledger IFRS",
        "34C": "Debt and Investment Management - Group Ledger US GAAP",
        "1WV": "Debt and Investment Management",
        "1S2": "Digital Payments",
        "5XU": "Document and Reporting Compliance",
        "2RP": "Electronic Documents",
        "1WC": "Embargo Control",
        "3F0": "Event-Based Production Cost Posting",
        "4GR": "Event-Based Revenue Recognition - Project-Based Sales - IFRS",
        "4GS": "Event-Based Revenue Recognition - Project-Based Sales - US GAAP",
        "4GQ": "Event-Based Revenue Recognition - Project-Based Sales",
        "1P0": "Event-Based Revenue Recognition - Project-Based Services - IFRS",
        "33O": "Event-Based Revenue Recognition - Project-Based Services - US GAAP",
        "1IL": "Event-Based Revenue Recognition - Project-Based Services",
        "33M": "Event-Based Revenue Recognition - Sell from Stock - IFRS",
        "33J": "Event-Based Revenue Recognition - Sell from Stock - US GAAP",
        "1K2": "Event-Based Revenue Recognition - Sell from Stock",
        "3M4": "Event-Based Revenue Recognition - Service Documents - IFRS",
        "3M5": "Event-Based Revenue Recognition - Service Documents - US GAAP",
        "3M3": "Event-Based Revenue Recognition - Service Documents",
        "5DR": "Event-Based Revenue Recognition - Subscription Billing - IFRS",
        "5DS": "Event-Based Revenue Recognition - Subscription Billing - US GAAP",
        "5DQ": "Event-Based Revenue Recognition - Subscription Billing",
        "2M0": "External Customer Payments",
        "2LZ": "External Digital Payments",
        "2OO": "External Tax Audit",
        "1HB": "Financial Plan Data Upload from File",
        "2FM": "Financial Planning and Analysis",
        "2UP": "Fixed Asset Tax Credit",
        "1X9": "Foreign Currency Risk Management - Group Ledger IFRS",
        "34D": "Foreign Currency Risk Management - Group Ledger US GAAP",
        "1X1": "Foreign Currency Risk Management",
        "5W6": "Foreign Trade for Procurement",
        "1GI": "General Ledger Allocation Cycle",
        "5PU": "Group Financial Planning",
        "2U6": "Group Reporting - Data from External Systems",
        "287": "Group Reporting - Data from SAP Group Reporting Data Collection",
        "1SG": "Group Reporting - Financial Consolidation",
        "28B": "Group Reporting - Plan Consolidation",
        "5W2": "Group Valuation",
        "1XD": "Hedge Accounting for FX Forward - Group Ledger IFRS",
        "3X3": "Hedge Accounting for FX Forward - Group Ledger US GAAP",
        "3X1": "Hedge Accounting for FX Forward - Local GAAP",
        "2RW": "Hedge Accounting for FX Option - Group Ledger IFRS",
        "3X4": "Hedge Accounting for FX Option - Group Ledger US GAAP",
        "3X2": "Hedge Accounting for FX Option - Local GAAP",
        "2UF": "Hedge Accounting for FX Swap - Group Ledger IFRS",
        "4RC": "Integrated Financial Planning"
    },
    "Human Resources": {
        "JB1": "Core HR with SAP SuccessFactors Employee Central",
        "1FD": "Employee Integration - SAP S/4HANA Enablement",
        "3UP": "Payroll Processing with SAP ERP HCM Payroll",
        "1NL": "Payroll Processing with SAP SuccessFactors Employee Central Payroll",
        "J12": "Time Recording - Project-Based Services",
        "1Q4": "Time Recording"
    },
    "IT Management": {
        "1LQ": "Output Management"
    },
    "Manufacturing": {
        "BLF": "Batch Management",
        "4C8": "Compliance Management for Environment, Health, and Safety",
        "1Y2": "Demand-Driven Buffer Level Management",
        "2QI": "Demand-Driven Replenishment Planning and Execution",
        "4XD": "Emissions Management",
        "4R8": "Engineer-to-Order Production with Variant Configuration",
        "54A": "Health and Safety Management",
        "3UK": "Inbound Storage Tank Management - Process Manufacturing",
        "3FP": "Lean Incident Management Reporting",
        "4YX": "Lean Management of Change Process",
        "55E": "Lot Size of One with Advanced Variant Configuration",
        "BJE": "Make-to-Order Production - Finished Goods Sales and Final Assembly",
        "3OK": "Make-to-Order Production - Process Manufacturing",
        "1BM": "Make-to-Order Production - Semifinished Goods Planning and Assembly",
        "4OC": "Make-to-Order Production for Sales Kits with Variant Configuration",
        "1YT": "Make-to-Order Production with Variant Configuration",
        "BJ8": "Make-to-Stock - Process Manufacturing Based on Process Order",
        "2UG": "Make-to-Stock - Process Manufacturing Based on Production Order",
        "BJ5": "Make-to-Stock Production - Discrete Manufacturing",
        "BJH": "Make-to-Stock Production - Repetitive Manufacturing",
        "21D": "Make-to-Stock Production with Variant Configuration",
        "3L7": "Make-to-Stock with Co- and By-Products - Process Manufacturing",
        "3UL": "Make-to-Stock with Silo Material - Process Manufacturing",
        "1E3": "Material Replenishment with Kanban - External Procurement",
        "4B3": "Material Replenishment with Kanban - In-House Production",
        "4B4": "Material Replenishment with Kanban - Stock Transfer",
        "J44": "Material Requirements Planning",
        "2QN": "Nonconformance Management",
        "20N": "Predictive Analytics Model Training - Supply Chain",
        "4B5": "Predictive Material and Resource Planning",
        "54U": "Produce and Sell Standard Products - Inventory Management",
        "54V": "Produce and Sell Standard Products - Warehouse Managed",
        "31L": "Production Capacity Evaluation",
        "3LQ": "Production Capacity Leveling",
        "1Y5": "Production Operations with Manufacturing Execution System",
        "2RU": "Production Order Processing with Third-Party Warehouse Management",
        "BJK": "Production Subcontracting - External Processing",
        "2F9": "Quality Management for Complaints Against Suppliers",
        "2FA": "Quality Management for Complaints from Customers",
        "1E1": "Quality Management in Discrete Manufacturing",
        "1FM": "Quality Management in Procurement",
        "1MP": "Quality Management in Sales",
        "1MR": "Quality Management in Stock Handling",
        "2QP": "Quality Management of Internal Problems",
        "BJN": "Rework Processing - Stock-Manufactured Material",
        "BJQ": "Rework Processing - Work-in-Process",
        "2JD": "SAP Fiori Analytical Apps for Production Planning",
        "2V0": "SAP Fiori Analytical Apps for Quality Management",
        "BLL": "Serial Number Management in Logistics",
        "BMY": "Subcontracting",
        "21T": "Subsidiary as Production Unit and Internal Supplier to Headquarters",
        "3W4": "Third-Party Shop Floor Execution - Discrete Industry",
        "3W3": "Third-Party Shop Floor Execution - Process Industry",
        "60H": "Waste Management"
    },
    "R&D/Engineering": {
        "3FC": "Assess Dangerous Goods for a Product",
        "31H": "Assess Marketability of a Product",
        "64F": "Bill of Material Management",
        "31G": "Chemical Compliance Approval for Purchased Material and Supplier",
        "31J": "Chemical Compliance in the Value Chain",
        "6JN": "Collaborative Project Management",
        "3G8": "Dangerous Goods in the Value Chain",
        "4R8": "Engineer-to-Order Production with Variant Configuration",
        "6MT": "Label Management",
        "55E": "Lot Size of One with Advanced Variant Configuration",
        "1YT": "Make-to-Order Production with Variant Configuration",
        "21D": "Make-to-Stock Production with Variant Configuration",
        "22P": "Manage Documents",
        "3VR": "Manage Safety Data Sheets for Products",
        "6U3": "PLM Integration with SAP Integrated Product Development",
        "6U2": "PLM System Integration",
        "2XU": "Procurement of Materials with Variant Configuration",
        "64E": "Product Change Management with Change Records",
        "1NT": "Project Control - Finance",
        "4RF": "Project Control - Resourcing and Procurement",
        "35F": "Project Control – Capital Projects",
        "35E": "Project Control – Research and Development Projects",
        "4I9": "Project Control – Sales",
        "3W1": "Project Data Replication to Central Finance",
        "1YF": "Project Review",
        "3VQ": "Safety Data Sheets in the Value Chain",
        "22T": "Set Up Configurable Model Using Variant Configuration",
        "4OL": "Substance Volume Tracking",
        "5OJ": "Supplier Compliance in the Value Chain"
    },
    "Sales": {
        "3ZB": "Billing of Costs Between Affiliated Companies",
        "31J": "Chemical Compliance in the Value Chain",
        "2UV": "Combined Invoice - Goods and Service Items",
        "4X9": "Create Sales Orders from Unstructured Data",
        "1EZ": "Credit Memo Processing",
        "1IU": "Customer Consignment",
        "BKP": "Customer Returns",
        "3TE": "Customer Returns for Non-Stock and Service Materials",
        "5CX": "Customer Returns for Sales Kits",
        "1Z3": "Customer Returns with Direct Shipment from Customer to Supplier",
        "3G8": "Dangerous Goods in the Value Chain",
        "1F1": "Debit Memo Processing",
        "2UW": "Delivery of Goods on Behalf of Another Company",
        "1MI": "Delivery Processing Without Order Reference",
        "4R8": "Engineer-to-Order Production with Variant Configuration",
        "1Z6": "External Billing",
        "BKA": "Free Goods Processing",
        "BDA": "Free of Charge Delivery",
        "2EL": "Integration of Sales with External Buyers",
        "1P9": "Intercompany Stock Transfer",
        "BDD": "Lean Customer Returns",
        "1ZQ": "Logistics with Third-Party Warehouse Management",
        "1O0": "Planning Apps for Sales",
        "2YJ": "Predictive Analytics Model Training - Sales",
        "54U": "Produce and Sell Standard Products - Inventory Management",
        "54V": "Produce and Sell Standard Products - Warehouse Managed",
        "BDW": "Returnables Processing",
        "3VQ": "Safety Data Sheets in the Value Chain",
        "2EQ": "Sale of Services",
        "2TT": "Sales Commissions - External Sales Representative",
        "I9I": "Sales Contract Management",
        "1IQ": "Sales Inquiry",
        "BDN": "Sales of Non-Stock Item with Order-Specific Procurement",
        "73P": "Sales Order Automation",
        "BDH": "Sales Order Entry with One-Time Customer",
        "BKK": "Sales Order Fulfillment Monitoring and Operations",
        "2ET": "Sales Order Processing for Non-Stock Material",
        "31Q": "Sales Order Processing for Sales Kits",
        "BKJ": "Sales Order Processing with Customer Down Payment",
        "BKZ": "Sales Order Processing with Invoice List and Collective Billing",
        "BD3": "Sales Processing using Third-Party with Shipping Notification",
        "4R6": "Sales Processing using Third-Party with Variant Configuration",
        "BDG": "Sales Quotation",
        "1B6": "Sales Rebate Processing",
        "3NR": "Sales Scheduling Agreements",
        "1BS": "SAP Fiori Analytical Apps for Sales",
        "BD9": "Sell from Stock",
        "5MQ": "Sell from Stock with Valuated Stock in Transit",
        "4GT": "Solution Order Management",
        "6HY": "Solution Order Management with Advanced Variant Configuration",
        "57Z": "Subscription Management with Sales Billing"
    },
    "Service": {
        "4GG": "Credit and Debit Memo Processing for Service Management",
        "3XK": "In-House Repair",
        "3NI": "Procurement for Service Management",
        "4X5": "Recurring Services",
        "3MO": "Service Contract Management",
        "6GU": "Service Contract Management with Advanced Variant Configuration",
        "6GS": "Service Management with Advanced Variant Configuration",
        "43B": "Service Monitoring and Analytics",
        "3D2": "Service Order Management and Monitoring",
        "49X": "Service Order Processing with SAP Field Service Management",
        "4GA": "Service Quotation",
        "63Y": "Warranty Claim Management - Customer Claim Processing",
        "5HR": "Warranty Claim Management - Supplier Recovery Processing"
    },
    "Solutions for Specific Industries": {
        "J11": "Customer Project Management - Project-Based Services",
        "1P0": "Event-Based Revenue Recognition - Project-Based Services - IFRS",
        "33O": "Event-Based Revenue Recognition - Project-Based Services - US GAAP",
        "1IL": "Event-Based Revenue Recognition - Project-Based Services",
        "1A8": "Internal Project Management - Project-Based Services",
        "4E9": "Project Billing - Project-Based Services",
        "6JO": "Resource Management for Projects",
        "J14": "Sales Order Processing - Project-Based Services",
        "J13": "Service and Material Procurement - Project-Based Services"
    },
    "Sourcing and Procurement": {
        "5HP": "Advanced Intercompany Stock Transfer",
        "J82": "Automated Purchase-to-Pay with SAP Ariba Commerce Automation",
        "BLF": "Batch Management",
        "3ZB": "Billing of Costs Between Affiliated Companies",
        "2ME": "Central Purchase Contracts",
        "2XT": "Central Purchasing",
        "1XI": "Central Requisitioning",
        "3ZF": "Central Sourcing",
        "2TW": "Complementary Procurement Functions",
        "BNX": "Consumable Purchasing",
        "2R3": "Cross-Company Purchasing Organization",
        "2TX": "Direct Procurement with Inbound Delivery",
        "22K": "External Workforce Procurement via SAP Fieldglass",
        "5W6": "Foreign Trade for Procurement",
        "2NV": "Guided Buying Capability with SAP Ariba Buying",
        "3EN": "Guided Buying for Central Procurement with SAP Ariba Buying",
        "2EJ": "Integration of Procurement with External Suppliers",
        "2OQ": "Integration to SAP Enterprise Contract Assembly",
        "1P9": "Intercompany Stock Transfer",
        "1LE": "Invoice Processing by OpenText",
        "1ZQ": "Logistics with Third-Party Warehouse Management",
        "55E": "Lot Size of One with Advanced Variant Configuration",
        "3FY": "Prediction of Delivery Date for Purchase Order Items",
        "1QR": "Predictive Analytics for Purchase Contract Quantity Consumption",
        "J45": "Procurement of Direct Materials",
        "2XU": "Procurement of Materials with Variant Configuration",
        "22Z": "Procurement of Services",
        "54U": "Produce and Sell Standard Products - Inventory Management",
        "BMD": "Purchase Contract",
        "2R7": "Purchasing Rebate Processing",
        "1JI": "Real-Time Reporting and Monitoring for Procurement",
        "1XF": "Request for Price",
        "18J": "Requisitioning",
        "2UU": "Returnable Packaging to Vendor",
        "1XV": "SAP S/4HANA for Enterprise Contract Management",
        "2NY": "Scheduling Agreement for Consignment Procurement",
        "2NX": "Scheduling Agreement for Subcontracting Procurement",
        "BMR": "Scheduling Agreements in Procurement",
        "BLL": "Serial Number Management in Logistics",
        "BMY": "Subcontracting",
        "19E": "Supplier Classification and Segmentation",
        "5OJ": "Supplier Compliance in the Value Chain",
        "2LG": "Supplier Consignment",
        "SL4": "Supplier Evaluation and Performance Monitoring"
    },
    "Supply Chain": {
        "4GH": "Acquisition of Freight Invoices",
        "1JW": "Advanced Available-to-Promise Processing",
        "5HP": "Advanced Intercompany Stock Transfer",
        "J82": "Automated Purchase-to-Pay with SAP Ariba Commerce Automation",
        "2LN": "Basic Available-to-Promise Processing",
        "BLF": "Batch Management",
        "2TW": "Complementary Procurement Functions",
        "BMC": "Core Inventory Management",
        "1P7": "Cross-Plant Transfer Posting",
        "2TX": "Direct Procurement with Inbound Delivery",
        "5W6": "Foreign Trade for Procurement",
        "4MM": "Handling Unit Management",
        "1P9": "Intercompany Stock Transfer",
        "1ZQ": "Logistics with Third-Party Warehouse Management",
        "55E": "Lot Size of One with Advanced Variant Configuration",
        "63V": "Mobile RF Devices in Warehousing",
        "63W": "Mobile RF Devices in Warehousing with Production Integration",
        "63X": "Mobile RF Devices in Warehousing with Quality Management",
        "4LU": "Physical Inventory - Cycle Counting",
        "BML": "Physical Inventory - Inventory Count and Adjustment",
        "J45": "Procurement of Direct Materials",
        "54U": "Produce and Sell Standard Products - Inventory Management",
        "54V": "Produce and Sell Standard Products - Warehouse Managed",
        "2RU": "Production Order Processing with Third-Party Warehouse Management",
        "2F9": "Quality Management for Complaints Against Suppliers",
        "2FA": "Quality Management for Complaints from Customers",
        "1FM": "Quality Management in Procurement",
        "1MP": "Quality Management in Sales",
        "1MR": "Quality Management in Stock Handling",
        "3M0": "Quality Management in Warehousing",
        "4A2": "Replenishment in Warehousing",
        "3W0": "Resource Management in Warehousing",
        "BMK": "Return to Supplier",
        "2VN": "SAP EWM Integration - Batch Management",
        "2VO": "SAP EWM Integration - Customer Returns",
        "2VM": "SAP EWM Integration - Delivery-Based Production Integration",
        "2VJ": "SAP EWM Integration - Inbound Processing from Supplier",
        "2VK": "SAP EWM Integration - Outbound Processing to Customer",
        "2YL": "SAP EWM Integration - Warehouse Stock Handling",
        "BLL": "Serial Number Management in Logistics",
        "BME": "Stock Transfer with Delivery",
        "BMY": "Subcontracting",
        "2LG": "Supplier Consignment",
        "3BT": "Warehouse Ad Hoc Goods Issue",
        "41U": "Warehouse Goods Receipt from Repetitive Manufacturing",
        "3BR": "Warehouse Inbound Processing",
        "5HN": "Warehouse Inbound Processing with Synchronous Goods Receipt",
        "5OK": "Warehouse Internal Inspections",
        "3BW": "Warehouse Internal Repacking",
        "3VT": "Warehouse Kanban Supply into Production",
        "3BS": "Warehouse Outbound Processing",
        "3BX": "Warehouse Physical Inventory",
        "3BU": "Warehouse Posting Changes",
        "3DV": "Warehouse Production Integration",
        "5HO": "Warehouse Production Integration with Synchronous Goods Receipt"
    }

}
